version: "3"

services:
  api:
    build:
      context: ./app
    command: "uvicorn main:app --host 0.0.0.0 --port 8000 --reload --proxy-headers"
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./app:/app/app:ro
      - ./images:/app/images
    ports:
      - "8000:8000"
    env_file:
      - .env
    networks:
      - gm-internal

networks:
#  nginx-proxy:
#    external: true

  gm-internal:
    driver: bridge
